<?php
/**
 * Copyright © Rollpix. All rights reserved.
 * See LICENSE for license details.
 */

/**
 * @var \Rollpix\Payment\Block\Widget\Cart $block
 */
?>

<div data-mage-init='{"rollpixUi": {}}'>
    <div class="rollpix-widget"
         data-type="cart"
         data-amount="<?= $block->escapeHtmlAttr($block->getSubtotal()->jsonSerialize()); ?>"
         data-currency="<?= $block->escapeHtmlAttr($block->getCurrencyCode()); ?>">
    </div>
</div>
