<?php
/**
 * Copyright © Rollpix. All rights reserved.
 * See LICENSE for license details.
 */

/**
 * @var \Rollpix\Payment\Block\Widget\Product $block
 */

use Magento\Framework\Json\Helper\Data;

?>

<div data-mage-init='{"rollpixUi": <?= $this->helper(Data::class)->jsonEncode($block->getUiParams()) ?>}'>
    <div class="rollpix-widget"
         data-type="product"
         data-amount="<?= $block->escapeHtmlAttr($block->getFinalPrice()->jsonSerialize()); ?>",
         data-currency="<?= $block->escapeHtmlAttr($block->getCurrencyCode()); ?>">
    </div>
</div>
